### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eoussama** [eoussama/clave#2]
Brainstorm a catchy and simple logo.

- [x] Logo
- [x] Readme

**Comment by EOussama** [comment]
![1](https://github.com/EOussama/clave/assets/22644543/de5f275c-6e66-4c65-9489-f7c7b626172b)
![6](https://github.com/EOussama/clave/assets/22644543/3b58b210-9b7b-478a-9c11-9704b386860e)
![5](https://github.com/EOussama/clave/assets/22644543/f01980bc-9c1b-4de8-8a61-e4b8cdf58be7)
![4](https://github.com/EOussama/clave/assets/22644543/fbeffba8-373d-4999-85de-b5739e21e61a)
![3](https://github.com/EOussama/clave/assets/22644543/d4838051-a9db-4d0e-afbf-c43666a7c4d9)
![2](https://github.com/EOussama/clave/assets/22644543/3fe74117-c98f-4e5b-a888-95ef085a0912)
